In [2]:
import tensorflow as tf

In [3]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [4]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

In [5]:
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [6]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits) ,dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [7]:
# cost entropy cost / loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [9]:
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())

    for step in range(2001) :
        sess.run(optimizer, feed_dict={X : x_data, Y : y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X : x_data , Y : y_data}))

    print('--------------')

    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X : [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')

    all = sess.run(hypothesis, feed_dict={
        X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 8.63453
200 0.5436762
400 0.44466484
600 0.36897355
800 0.29637718
1000 0.23792024
1200 0.21531153
1400 0.1965664
1600 0.18073115
1800 0.16718084
2000 0.1554596
--------------
[[6.5021003e-03 9.9348783e-01 1.0045675e-05]] [1]
--------------
[[0.8391308  0.14354977 0.0173194 ]] [0]
--------------
[[1.2805473e-08 3.5080142e-04 9.9964917e-01]] [2]
--------------
[[6.50210027e-03 9.93487835e-01 1.00456755e-05]
 [8.39130819e-01 1.43549770e-01 1.73194036e-02]
 [1.28054731e-08 3.50801420e-04 9.99649167e-01]] [1 0 2]
